/**
 * Marketing Research Visualizer Component
 * 
 * This component displays visualizations generated by the marketing research agent,
 * including charts, sentiment analysis, and keyword data.
 */

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { BarChart, PieChart, LineChart } from 'lucide-react';
import { SentimentAnalysis } from './SentimentAnalysis';
import { KeywordCloud } from './KeywordCloud';

interface ChartData {
  [key: string]: string; // Chart title -> base64 image data
}

interface SentimentData {
  compound: number;
  pos: number;
  neu: number;
  neg: number;
}

interface MarketingResearchVisualizerProps {
  charts?: ChartData;
  sentiment?: SentimentData;
  keywords?: Array<[string, number]>; // [keyword, frequency]
  className?: string;
}

export const MarketingResearchVisualizer: React.FC<MarketingResearchVisualizerProps> = ({
  charts = {},
  sentiment,
  keywords = [],
  className = '',
}) => {
  const chartTitles = Object.keys(charts);
  
  if (!chartTitles.length && !sentiment && !keywords.length) {
    return null; // Don't render if no data
  }

  return (
    <div className={`marketing-research-visualizer ${className}`}>
      {/* Render charts */}
      {chartTitles.length > 0 && (
        <div className="marketing-charts-container">
          {chartTitles.map((title) => (
            <Card key={title} className="marketing-chart-card">
              <CardHeader className="pb-2">
                <CardTitle className="text-md flex items-center">
                  {title.includes('Sentiment') ? (
                    <BarChart className="h-4 w-4 mr-2" />
                  ) : title.includes('Keyword') ? (
                    <PieChart className="h-4 w-4 mr-2" />
                  ) : (
                    <LineChart className="h-4 w-4 mr-2" />
                  )}
                  {title}
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <img
                  src={`data:image/png;base64,${charts[title]}`}
                  alt={title}
                  className="marketing-chart-image"
                />
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Render sentiment analysis */}
      {sentiment && (
        <SentimentAnalysis sentiment={sentiment} className="mt-4" />
      )}

      {/* Render keyword cloud */}
      {keywords.length > 0 && (
        <KeywordCloud keywords={keywords} className="mt-4" />
      )}
    </div>
  );
};

export default MarketingResearchVisualizer;
